[buildPlans.Iosevka]
family = "Iosevka"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

  [buildPlans.Iosevka.variants]
  inherits = "ss12"

    [buildPlans.Iosevka.variants.design]
    one = "no-base"
    two = "straight-neck-serifless"
    three = "flat-top-serifless"
    four = "closed-non-crossing-serifless"
    five = "upright-flat-serifless"
    six = "straight-bar"
    seven = "straight-serifless"
    eight = "two-circles"
    nine = "straight-bar"
    zero = "slashed"
    capital-g = "toothless-rounded-serifless-hooked"
    capital-i = "short-serifed"
    capital-j = "serifed"
    capital-s = "serifless"
    a = "double-storey-serifless"
    g = "double-storey"
    i = "tailed-serifed"
    j = "serifed"
    l = "tailed-serifed"
    r = "compact-serifless"
    cyrl-capital-u = "straight-serifless"
    cyrl-che = "standard"
    punctuation-dot = "round"
    tilde = "low"
    asterisk = "hex-low"
    ascii-grave = "straight"
    ascii-single-quote = "straight"
    paren = "normal"
    brace = "straight"
    dollar = "through"
    percent = "rings-continuous-slash"
    bar = "natural-slope"

  [buildPlans.Iosevka.ligations]
  inherits = "dlig"
